name: Ensure major version tags

on:
  workflow_call: {}

permissions: {}

jobs:
  debug_info:
    name: Debug info
    runs-on: ubuntu-24.04
    steps:
      - name: Print github context JSON
        run: |
          cat <<EOF
          ${{ toJson(github) }}
          EOF
  ensure_major_version_tags:
    name: Ensure major version tags
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: giantswarm/floating-tags-action@ce8d4d60ddeaf45623e82954987f1644775db3f1 # v1.2.0
