name: Gitleaks

on:
  workflow_call: {}

permissions: {}

jobs:
  gitleaks:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: '0'
      - name: gitleaks-action
        uses: giantswarm/gitleaks-action@main
