name: Release Please

on:
  workflow_call:
    secrets:
      TAYLORBOT_GITHUB_ACTION:
        required: true
    outputs:
      release_created:
        description: "Set to 'true' if a release was created."
        value: ${{ jobs.release_please.outputs.release_created }}
      tag_name:
        description: "Tag name of the created release, e.g. v1.2.3."
        value: ${{ jobs.release_please.outputs.tag_name }}
      major:
        description: "Major version component of the created release."
        value: ${{ jobs.release_please.outputs.major }}
      minor:
        description: "Minor version component of the created release."
        value: ${{ jobs.release_please.outputs.minor }}
      patch:
        description: "Patch version component of the created release."
        value: ${{ jobs.release_please.outputs.patch }}
      pr:
        description: "Release Please PR number (open when no release was created yet)."
        value: ${{ jobs.release_please.outputs.pr }}

permissions: {}

jobs:
  release_please:
    name: Release Please
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
    outputs:
      release_created: ${{ steps.release_please.outputs.release_created }}
      tag_name: ${{ steps.release_please.outputs.tag_name }}
      major: ${{ steps.release_please.outputs.major }}
      minor: ${{ steps.release_please.outputs.minor }}
      patch: ${{ steps.release_please.outputs.patch }}
      pr: ${{ steps.release_please.outputs.pr }}
    steps:
      - name: Run Release Please
        id: release_please
        uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        with:
          token: ${{ secrets.TAYLORBOT_GITHUB_ACTION }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
