name: Semantic Pull Request

on:
  workflow_call: {}

permissions: {}

jobs:
  semantic-pull-request:
    name: Validate PR title
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: read
    steps:
      - name: Validate PR title follows Conventional Commits
        if: github.event_name == 'pull_request'
        uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
