name: Fix Vulnerabilities

on:
  workflow_call:
    inputs:
      branch:
        description: "Branch on which to fix vulnerabilities"
        required: true
        type: string

jobs:
  gather_facts:
    name: Gather facts
    runs-on: ubuntu-22.04
    outputs:
      branch: ${{ steps.gather_facts.outputs.branch }}
      skip:   ${{ steps.gather_facts.outputs.skip }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ inputs.branch }}
      - name: Gather facts
        id: gather_facts
        run: |
          head="${{ inputs.branch }}"
          branch="${{ github.ref_name }}"
          echo "branch=${branch}" >> $GITHUB_OUTPUT
          head="${head#refs/heads/}"
          echo "head=${head}"   >> $GITHUB_OUTPUT
          if [[ ! -e go.mod && ! -e go.sum ]]; then
            echo "skip=true"    >> $GITHUB_OUTPUT
          else
            echo "skip=false"   >> $GITHUB_OUTPUT
          fi

  run_nancy_fixer:
    name: Fix vulnerabilities with nancy-fixer
    runs-on: ubuntu-22.04
    needs: gather_facts
    if: ${{ needs.gather_facts.outputs.skip != 'true' }}
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v2.0.2
        with:
          app-id:      ${{ secrets.HERALD_APP_ID }}
          private-key: ${{ secrets.HERALD_APP_KEY }}

      - name: Checkout code with token
        uses: actions/checkout@v4.2.2
        with:
          token:                 ${{ steps.generate_token.outputs.token }}
          persist-credentials:   false
          ref:                   ${{ needs.gather_facts.outputs.branch }}

      - name: Create new branch
        id: create_branch
        run: |
          branch="remediate-vulnerabilities-${{ needs.gather_facts.outputs.branch }}"
          echo "branch=${branch}" >> $GITHUB_OUTPUT
          git checkout -b "${branch}"
          git pull origin "${branch}" || true

      - name: Run nancy-fixer fix
        uses: docker://gsoci.azurecr.io/giantswarm/nancy-fixer:0.4.4
        timeout-minutes: 20

      - name: Commit & push
        run: |
          git config user.email  "149080493+heraldbot[bot]@users.noreply.github.com"
          git config user.name   "HeraldBot[bot]"
          git add -A
          if git diff-index --quiet HEAD; then
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            git commit -m "Remediate Nancy findings"
            echo "skip=false" >> $GITHUB_OUTPUT
            git push "https://${{ github.actor }}:${{ steps.generate_token.outputs.token }}@github.com/${{ github.repository }}.git" \
                     HEAD:"${{ steps.create_branch.outputs.branch }}"
          fi

      - name: Create PR
        if: ${{ steps.commit_changes.outputs.skip != 'true' }}
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          gh pr create \
            --title "Remediate Nancy findings on ${{ needs.gather_facts.outputs.branch }}" \
            --body  "Fix Nancy findings on branch ${{ needs.gather_facts.outputs.branch }}" \
            --head  ${{ steps.create_branch.outputs.branch }} \
            --base  ${{ needs.gather_facts.outputs.branch }} \
          && gh pr merge --auto --squash
