name: Gitleaks

on:
  workflow_call: {}

jobs:
  gitleaks:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: '0'
      - name: Run gitleaks
        uses: giantswarm/gitleaks-action@main
